import { useEffect, useState } from 'react';
import { AccessibilityInfo, StyleSheet, useWindowDimensions } from 'react-native';
import * as SplashScreen from 'expo-splash-screen';
import Animated, {
  Easing,
  interpolate,
  runOnJS,
  useAnimatedProps,
  useAnimatedStyle,
  useDerivedValue,
  useSharedValue,
  withDelay,
  withTiming,
  Extrapolation,
} from 'react-native-reanimated';
import Svg, { Circle, ClipPath, Defs, G, LinearGradient, Path, Rect, Stop } from 'react-native-svg';

import { Brand, Mark, Type } from '@/constants/brand';
import { RELAXED, pulse, toPath } from '@/lib/bellMorph';

const AnimatedPath = Animated.createAnimatedComponent(Path);
const AnimatedG = Animated.createAnimatedComponent(G);
const AnimatedRect = Animated.createAnimatedComponent(Rect);
const AnimatedCircle = Animated.createAnimatedComponent(Circle);

/**
 * Which frame the OS holds before any JS runs.
 *
 * `still` is the sequence's resting mark, which is what app.json ships and what
 * makes the handoff invisible: our view mounts drawing the identical frame, so
 * swapping one for the other shows nothing. The cost is that the build-up -
 * the play triangle appearing, the bell irising out of it - has already
 * happened by the time anyone can see it, so on a cold launch it is not seen.
 *
 * `seed` trades that the other way: point the plugin at `assets/splash-seed.png`
 * instead and the OS holds frame 0, our view mounts on frame 0, and the whole
 * build-up plays where a user can watch it. Still no seam, because the frames
 * still match - it is a different frame that matches.
 *
 * Both PNGs are generated by `npm run brand`, so this is a two-line change.
 */
const LAUNCH_FRAME: 'still' | 'seed' = 'still';

/*
 * The beats, in seconds, exactly as SPLASH.md gives them.
 *
 * One adjustment, and it is worth knowing about: the spec calls 1.50s the
 * resting frame, but three beats it lists are still running then - the veil
 * lands at 1.46, the level line at 1.62, the wordmark at 1.60 and the subtitle
 * at 1.82. Rest cannot be before the things that constitute it have finished,
 * so rest here is when the last beat lands, and the two exit beats keep their
 * spacing *relative to rest* (press at rest + 0.12, swim at rest + 0.42) -
 * which is how their absolute times in the spec were derived in the first
 * place, on the assumption that nothing holds.
 */
const BEATS = {
  play: { at: 0.0, dur: 0.42 },
  iris: { at: 0.46, dur: 0.72 },
  knockout: { at: 0.54, dur: 0.2 },
  veil: { at: 0.78, dur: 0.68 },
  line: { at: 0.96, dur: 0.66 },
  word: { at: 0.0, dur: 0.54 },   // on the text clock
  sub: { at: 0.18, dur: 0.58 },   // on the text clock
};
const MARK_END = BEATS.line.at + BEATS.line.dur;   // 1.62
const TEXT_END = BEATS.sub.at + BEATS.sub.dur;     // 0.76
const PRESS_DUR = 0.26;
const SWIM_DUR = 2.6;

/** One ease for the whole sequence, per the kit's motion rule. */
const EASE = Easing.bezier(0.22, 1, 0.36, 1);

/**
 * The same curve's shape, as a plain worklet.
 *
 * `Easing.bezier` returns a factory for `withTiming` to consume, not something
 * callable on the UI thread - so anything easing a value by hand inside a
 * worklet needs this instead.
 */
function easeOut(x: number): number {
  'worklet';
  return 1 - Math.pow(1 - Math.min(1, Math.max(0, x)), 3);
}

/*
 * The swim, from five numbers rather than authored keyframes, so the exit
 * direction stays a runtime value rather than something baked into a curve.
 */
const SWIM = {
  heading: -Math.PI / 2,  // straight up, in view space
  sway: 0.2,              // perpendicular, as a fraction of travel
  cycles: 4,
  duration: SWIM_DUR,
  distance: 620,
};

type Props = {
  /** Held at the resting frame until this is true. Never gates startup. */
  ready: boolean;
  onFinish: () => void;
};

export default function SplashSequence({ ready, onFinish }: Props) {
  const { width, height } = useWindowDimensions();
  const [reduceMotion, setReduceMotion] = useState<boolean | null>(null);

  // The mark clock. Starts at the end when the OS is already holding the
  // resting frame, so our first painted frame is identical to the still.
  const markT = useSharedValue(LAUNCH_FRAME === 'still' ? MARK_END : 0);
  const textT = useSharedValue(0);
  const swimT = useSharedValue(0);
  const press = useSharedValue(0);
  const fade = useSharedValue(1);

  useEffect(() => {
    let alive = true;
    AccessibilityInfo.isReduceMotionEnabled().then(v => {
      if (alive) setReduceMotion(v);
    });
    return () => {
      alive = false;
    };
  }, []);

  // The intro. Reduced motion skips it: the resting frame is already what is
  // on screen, so there is nothing to play.
  useEffect(() => {
    if (reduceMotion === null) return;
    if (reduceMotion) return;
    if (LAUNCH_FRAME === 'seed') {
      markT.value = withTiming(MARK_END, { duration: MARK_END * 1000, easing: Easing.linear });
      textT.value = withDelay(
        BEATS.word.at * 1000 + 1060,
        withTiming(TEXT_END, { duration: TEXT_END * 1000, easing: Easing.linear }),
      );
    } else {
      textT.value = withTiming(TEXT_END, { duration: TEXT_END * 1000, easing: Easing.linear });
    }
  }, [reduceMotion, markT, textT]);

  // The exit. Runs only once the app behind it is actually ready, which is why
  // a slow launch holds a still, correct frame rather than gating on animation.
  useEffect(() => {
    if (!ready || reduceMotion === null) return;

    if (reduceMotion) {
      fade.value = withTiming(0, { duration: 240, easing: EASE }, done => {
        if (done) runOnJS(onFinish)();
      });
      return;
    }

    press.value = withDelay(
      120,
      withTiming(1, { duration: PRESS_DUR * 1000, easing: EASE }),
    );
    swimT.value = withDelay(
      420,
      withTiming(1, { duration: SWIM_DUR * 1000, easing: Easing.linear }, done => {
        if (done) runOnJS(onFinish)();
      }),
    );
    fade.value = withDelay(
      420 + SWIM_DUR * 1000 - 500,
      withTiming(0, { duration: 500, easing: EASE }),
    );
  }, [ready, reduceMotion, press, swimT, fade, onFinish]);

  /*
   * The trajectory, derived rather than keyframed.
   *
   * Travel accumulates only during the thrust of each pulse. Sway is
   * perpendicular to the heading at 20% of travel - below about 10% the eye
   * reads a straight line - and reverses only between pulses, because a jelly
   * steers by aiming its next squeeze, not mid-glide.
   */
  const swim = useDerivedValue(() => {
    const p = swimT.value * SWIM.cycles;
    const index = Math.floor(p);
    const phase = p - index;
    const { shape, push } = pulse(phase);

    const travelled = (index + push) / SWIM.cycles;
    const along = travelled * SWIM.distance;
    const direction = index % 2 === 0 ? 1 : -1;
    const lateral =
      Math.sin(travelled * Math.PI * SWIM.cycles) * SWIM.sway * SWIM.distance * direction;

    return { shape, along, lateral };
  });

  const bellProps = useAnimatedProps(() => {
    // Iris: the bell grows out of the play triangle's own centre, so the two
    // shapes are never briefly unrelated.
    const iris = interpolate(
      markT.value,
      [BEATS.iris.at, BEATS.iris.at + BEATS.iris.dur],
      [0, 1],
      Extrapolation.CLAMP,
    );
    return {
      d: toPath(swimT.value > 0 ? swim.value.shape : RELAXED),
      opacity: iris,
    };
  });

  const bellIrisStyle = useAnimatedProps(() => {
    const iris = interpolate(
      markT.value,
      [BEATS.iris.at, BEATS.iris.at + BEATS.iris.dur],
      [0, 1],
      Extrapolation.CLAMP,
    );
    const eased = easeOut(iris);
    return {
      transform: `translate(${Mark.playCentre.x} ${Mark.playCentre.y}) scale(${eased}) translate(${-Mark.playCentre.x} ${-Mark.playCentre.y})`,
    };
  });

  const playProps = useAnimatedProps(() => {
    const fadeIn = interpolate(
      markT.value,
      [BEATS.play.at, BEATS.play.at + BEATS.play.dur],
      [0, 1],
      Extrapolation.CLAMP,
    );
    return { opacity: fadeIn };
  });

  // The knockout flip: the triangle stops being a gradient shape and becomes a
  // hole. Two stacked paths cross-fade, which is how it stays a knockout at
  // every point in between rather than briefly becoming a third colour.
  const knockoutProps = useAnimatedProps(() => {
    const k = interpolate(
      markT.value,
      [BEATS.knockout.at, BEATS.knockout.at + BEATS.knockout.dur],
      [0, 1],
      Extrapolation.CLAMP,
    );
    return { opacity: k };
  });

  const veilProps = useAnimatedProps(() => {
    const rise = interpolate(
      markT.value,
      [BEATS.veil.at, BEATS.veil.at + BEATS.veil.dur],
      [300, 0],
      Extrapolation.CLAMP,
    );
    return { transform: `translate(0 ${rise})` };
  });

  const lineProps = useAnimatedProps(() => {
    const draw = interpolate(
      markT.value,
      [BEATS.line.at, BEATS.line.at + BEATS.line.dur],
      [0, 1],
      Extrapolation.CLAMP,
    );
    const w = 512 * draw;
    return { x: (512 - w) / 2, width: w };
  });

  // Press: the whole mark dips, and a ring pushes out of the play hole.
  const markStyle = useAnimatedStyle(() => {
    // Press: the mark dips and comes back, so the dip is a half sine rather
    // than a ramp - it must end where it started.
    const dip = 1 - 0.038 * Math.sin(press.value * Math.PI);
    const { along, lateral } = swim.value;

    // Travel along the heading, sway perpendicular to it. Written as vectors
    // rather than as x/y so that `heading` stays a real runtime parameter -
    // hardcoding "up" here is what would bake the exit direction back in.
    const cos = Math.cos(SWIM.heading);
    const sin = Math.sin(SWIM.heading);
    const x = cos * along - sin * lateral;
    const y = sin * along + cos * lateral;

    // Bank from lateral velocity, so the tilt leads each turn instead of
    // trailing it.
    const bank = interpolate(lateral, [-120, 120], [-7, 7], Extrapolation.CLAMP);
    return {
      transform: [
        { translateX: x },
        { translateY: y },
        { rotateZ: `${bank}deg` },
        { scale: dip },
      ],
    };
  });

  const ringProps = useAnimatedProps(() => ({
    r: interpolate(press.value, [0, 1], [0, 260], Extrapolation.CLAMP),
    opacity: interpolate(press.value, [0, 0.4, 1], [0, 0.5, 0], Extrapolation.CLAMP),
  }));

  const wordStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      textT.value,
      [BEATS.word.at, BEATS.word.at + BEATS.word.dur],
      [0, 1],
      Extrapolation.CLAMP,
    ),
    transform: [
      {
        translateY: interpolate(
          textT.value,
          [BEATS.word.at, BEATS.word.at + BEATS.word.dur],
          [9, 0],
          Extrapolation.CLAMP,
        ),
      },
    ],
  }));

  const subStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      textT.value,
      [BEATS.sub.at, BEATS.sub.at + BEATS.sub.dur],
      [0, 0.72],
      Extrapolation.CLAMP,
    ),
  }));

  const rootStyle = useAnimatedStyle(() => ({ opacity: fade.value }));

  if (reduceMotion === null) return null;

  // 200pt, matching the plugin's imageWidth, so our mark lands where the OS
  // drew the still's.
  const size = 200;

  return (
    <Animated.View
      style={[styles.root, { width, height }, rootStyle]}
      pointerEvents="none"
      onLayout={() => {
        // Hide the native still only once our own view has laid out, so the two
        // swap with nothing in between.
        SplashScreen.hideAsync().catch(() => {});
      }}
    >
      <Animated.View style={[styles.mark, { width: size, height: size }, markStyle]}>
        <Svg width={size} height={size} viewBox="0 0 512 512">
          <Defs>
            {/*
              Pinned in the bell's own 1024 space. Pinning it to the 512 tile
              instead lands the whole gradient span in one corner of the bell
              and clamps the mark to flat blue.
            */}
            <LinearGradient
              id="g"
              gradientUnits="userSpaceOnUse"
              x1={Mark.gradient.x1}
              y1={Mark.gradient.y1}
              x2={Mark.gradient.x2}
              y2={Mark.gradient.y2}
            >
              <Stop offset="0" stopColor={Brand.glyphFrom} />
              <Stop offset="1" stopColor={Brand.glyphTo} />
            </LinearGradient>
            <ClipPath id="cb">
              <Path d={Mark.bell} />
            </ClipPath>
          </Defs>

          <G transform={Mark.splashTransform}>
            <G transform={Mark.tileTransform}>
              <AnimatedG animatedProps={bellIrisStyle}>
                <AnimatedPath animatedProps={bellProps} fill="url(#g)" />
                <G clipPath="url(#cb)">
                  <AnimatedPath
                    animatedProps={veilProps}
                    d={Mark.veil}
                    fill={Brand.substrate}
                    opacity={Mark.veilOpacity}
                  />
                </G>
              </AnimatedG>

              {/* Frame 0: the triangle as a gradient shape of its own. */}
              <AnimatedPath animatedProps={playProps} d={Mark.play} fill="url(#g)" />
              {/* The knockout it becomes. Substrate-filled, never a third colour. */}
              <AnimatedPath animatedProps={knockoutProps} d={Mark.play} fill={Brand.substrate} />

              {/* The press ring, pushed out of the play hole's own centre. */}
              <AnimatedCircle
                animatedProps={ringProps}
                cx={Mark.playCentre.x}
                cy={Mark.playCentre.y}
                fill="none"
                stroke={Brand.glyphTo}
                strokeWidth={8}
              />
            </G>
          </G>

          <AnimatedRect
            animatedProps={lineProps}
            y={Mark.levelLine.y}
            height={Mark.levelLine.height}
            fill={Mark.levelLine.color}
            opacity={Mark.levelLine.opacity}
          />
        </Svg>
      </Animated.View>

      <Animated.View style={styles.copy}>
        <Animated.Text style={[styles.word, wordStyle]}>JellyLab</Animated.Text>
        <Animated.Text style={[styles.sub, subStyle]}>Watch and request, in one place</Animated.Text>
      </Animated.View>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  root: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Brand.substrate,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mark: { alignItems: 'center', justifyContent: 'center' },
  copy: { position: 'absolute', bottom: '18%', alignItems: 'center' },
  word: {
    fontFamily: Type.display,
    fontSize: 28,
    letterSpacing: Type.displayTracking(28),
    color: Brand.text,
  },
  sub: {
    fontFamily: Type.mono,
    fontSize: 11,
    letterSpacing: Type.monoTracking(11),
    textTransform: 'uppercase',
    color: Brand.text2,
    marginTop: 10,
  },
});
