#!/usr/bin/env node
/**
 * Regenerate the app's image assets from the brand kit.
 *
 * `brand-kit/` is the source of truth and is never written to. Everything in
 * `assets/images/` is generated by this script, so changing the logo means
 * dropping a new kit into `brand-kit/` and running `npm run brand` - not
 * hand-exporting eight sizes and hoping they stay in step.
 *
 * The kit ships SVG only, on purpose: the mark is flat and geometric, so every
 * size is a fresh render rather than a resample, and the platform layers
 * (Android's three, iOS's appearances) stay separate files instead of being
 * composited here. Rendering is resvg, which honours the user-space gradients
 * the kit pins across the whole tile.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import { PNG } from 'pngjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const p = (...s) => resolve(ROOT, ...s);

const render = (name, size) =>
  PNG.sync.read(
    new Resvg(readFileSync(p('brand-kit/svg', `${name}.svg`), 'utf8'), {
      fitTo: { mode: 'width', value: size },
    })
      .render()
      .asPng(),
  );

function write(png, dst, opts = {}) {
  mkdirSync(dirname(p(dst)), { recursive: true });
  writeFileSync(p(dst), PNG.sync.write(png, opts));
  const kb = Math.round(readFileSync(p(dst)).length / 1024);
  console.log(`  ${dst.padEnd(46)} ${png.width}x${png.height} ${kb}KB`);
}

const hexToRgb = hex => [0, 2, 4].map(i => parseInt(hex.replace('#', '').slice(i, i + 2), 16));
const rgbToHex = rgb => '#' + rgb.map(v => v.toString(16).padStart(2, '0').toUpperCase()).join('');

/** The substrate, read off the rendered tile rather than written down, so it
 * cannot drift from the artwork the way a second copy of a hex would. The kit
 * gives it flat, but this samples anyway: it is what the splash ground, the
 * adaptive icon's fallback and web theme-color all have to match, and sampling
 * keeps that true if the plate ever goes back to being a gradient. */
function substrate() {
  const img = render('icon-dark', 512);
  const i = (512 * 4 + 4) << 2;  // a corner, which a gradient plate would differ at
  return rgbToHex([img.data[i], img.data[i + 1], img.data[i + 2]]);
}

/**
 * Composite onto a solid background and drop the alpha channel entirely.
 *
 * App Store Connect rejects an icon that merely *has* an alpha channel, even
 * one that is opaque everywhere - so writing colorType 2 is the point of this,
 * not an optimisation.
 */
function flattenOpaque(name, size, dst, bgHex) {
  const img = render(name, size);
  const [br, bg, bb] = hexToRgb(bgHex);
  const out = new PNG({ width: img.width, height: img.height });
  for (let i = 0; i < img.data.length; i += 4) {
    const a = img.data[i + 3] / 255;
    out.data[i] = Math.round(img.data[i] * a + br * (1 - a));
    out.data[i + 1] = Math.round(img.data[i + 1] * a + bg * (1 - a));
    out.data[i + 2] = Math.round(img.data[i + 2] * a + bb * (1 - a));
    out.data[i + 3] = 255;
  }
  write(out, dst, { colorType: 2 });
}

console.log('brand-kit/ -> assets/images/');

const NIGHT = substrate();
console.log(`  substrate ${NIGHT} (app.json backgroundColor, theme.brand.substrate)`);

// iOS + App Store. Flattened: the render is RGBA, which App Store Connect refuses.
flattenOpaque('icon-dark', 1024, 'assets/images/icon.png', NIGHT);

// The icon as drawn inside the app - the About screen. 180 is the @3x home
// screen size, which is the largest anything on-screen asks for.
write(render('icon-dark', 180), 'assets/images/icon-180.png');

// Splash: the bare glyph, drawn over expo-splash-screen's backgroundColor.
write(render('glyph-gradient', 1024), 'assets/images/splash-icon.png');

// Android adaptive icon. All three layers are the kit's own - the foreground
// already carries the 66% safe-zone padding, so nothing is centred or scaled
// here, and the background is the substrate gradient rather than a flat fill.
write(render('android-foreground', 1024), 'assets/images/android-icon-foreground.png');
write(render('android-background', 1024), 'assets/images/android-icon-background.png');
write(render('android-monochrome', 1024), 'assets/images/android-icon-monochrome.png');

// The mark as drawn inside the app - currently the login header. 512 so it
// still has headroom at 3x on the largest phones.
write(render('glyph-gradient', 512), 'assets/images/mark.png');

// Web favicon. Larger than a favicon needs to be, so it stays sharp if Expo
// downsamples it for the tab and for the PWA install prompt.
write(render('icon-dark', 192), 'assets/images/favicon.png');

// apple-touch-icon, for a page saved to the home screen. iOS refuses an SVG
// here, composites any transparency over black, and crops the corners itself -
// so this is 180 square, opaque, and unpadded, exactly as the kit specifies.
// It lands in public/ because it has to be served at a fixed path for the
// <link> in app/+html.tsx; a bundled asset gets a hashed name instead.
flattenOpaque('icon-dark', 180, 'public/apple-touch-icon.png', NIGHT);

console.log('done');
