#!/usr/bin/env node
/**
 * Regenerate the app's image assets from the brand kit.
 *
 * `brand/` is the source of truth and is never written to. Everything in
 * `assets/images/` is generated by this script, so changing the logo means
 * dropping new files into `brand/` and running `npm run brand` - not
 * hand-exporting eight sizes and hoping they stay in step.
 *
 * Only compositing and alpha work happens here, never resampling: every size
 * the app needs already exists in the kit, so a source is picked at the right
 * size and pasted, which keeps the artwork bit-exact.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const p = (...s) => resolve(ROOT, ...s);

/**
 * Night, from BRAND.md. The kit specifies it as a gradient (#14121C -> #05070C)
 * because the icon tile is one; this is its midpoint, which is what anything
 * needing a single flat colour gets - splash ground, Android icon background,
 * web theme-color. Sampling the shipped icon returns exactly this value at the
 * tile's centre, so a flat splash sits flush against the icon rather than
 * reading as a slightly different black.
 */
const NIGHT = '#0D0D14';

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16));
}

const read = src => PNG.sync.read(readFileSync(p(src)));

function write(png, dst, opts = {}) {
  mkdirSync(dirname(p(dst)), { recursive: true });
  writeFileSync(p(dst), PNG.sync.write(png, opts));
  const kb = Math.round(readFileSync(p(dst)).length / 1024);
  console.log(`  ${dst.padEnd(44)} ${png.width}x${png.height} ${kb}KB`);
}

/**
 * Composite onto a solid background and drop the alpha channel entirely.
 *
 * App Store Connect rejects an icon that merely *has* an alpha channel, even
 * one that is opaque everywhere - so writing colorType 2 is the point of this,
 * not an optimisation.
 */
function flattenOpaque(src, dst, bgHex) {
  const img = read(src);
  const [br, bg, bb] = hexToRgb(bgHex);
  const out = new PNG({ width: img.width, height: img.height });
  for (let i = 0; i < img.data.length; i += 4) {
    const a = img.data[i + 3] / 255;
    out.data[i] = Math.round(img.data[i] * a + br * (1 - a));
    out.data[i + 1] = Math.round(img.data[i + 1] * a + bg * (1 - a));
    out.data[i + 2] = Math.round(img.data[i + 2] * a + bb * (1 - a));
    out.data[i + 3] = 255;
  }
  write(out, dst, { colorType: 2 });
}

/**
 * Paste a source into the middle of a transparent square.
 *
 * Android's adaptive icon crops the foreground to as little as the centre 66%,
 * so the mark is pasted at half the canvas and the rest is padding - which is
 * also why this never scales: a 512 source in a 1024 canvas is exactly the
 * safe size, with no resampling.
 */
function centerOn(src, size, dst, { tint } = {}) {
  const img = read(src);
  const out = new PNG({ width: size, height: size, fill: true });
  const ox = Math.round((size - img.width) / 2);
  const oy = Math.round((size - img.height) / 2);
  const rgb = tint ? hexToRgb(tint) : null;
  for (let y = 0; y < img.height; y++) {
    for (let x = 0; x < img.width; x++) {
      const s = (img.width * y + x) << 2;
      const dx = x + ox;
      const dy = y + oy;
      if (dx < 0 || dy < 0 || dx >= size || dy >= size) continue;
      const d = (size * dy + dx) << 2;
      out.data[d] = rgb ? rgb[0] : img.data[s];
      out.data[d + 1] = rgb ? rgb[1] : img.data[s + 1];
      out.data[d + 2] = rgb ? rgb[2] : img.data[s + 2];
      out.data[d + 3] = img.data[s + 3];
    }
  }
  write(out, dst);
}

function solid(size, hex, dst) {
  const [r, g, b] = hexToRgb(hex);
  const out = new PNG({ width: size, height: size });
  for (let i = 0; i < out.data.length; i += 4) {
    out.data[i] = r; out.data[i + 1] = g; out.data[i + 2] = b; out.data[i + 3] = 255;
  }
  write(out, dst, { colorType: 2 });
}

function copy(src, dst) {
  write(read(src), dst);
}

console.log('brand/ -> assets/images/');

// iOS + App Store. Flattened: the kit ships RGBA, which App Store Connect refuses.
flattenOpaque('brand/png/icon/icon-1024.png', 'assets/images/icon.png', NIGHT);

// Splash: the bare mark, drawn over expo-splash-screen's backgroundColor.
copy('brand/png/mark/jellylab-mark-dark-1024.png', 'assets/images/splash-icon.png');

// Android adaptive icon: foreground, its ground, and the themed-icon silhouette.
centerOn('brand/png/mark/jellylab-mark-dark-512.png', 1024, 'assets/images/android-icon-foreground.png');
solid(1024, NIGHT, 'assets/images/android-icon-background.png');
centerOn('brand/png/mark/jellylab-mark-dark-512.png', 1024, 'assets/images/android-icon-monochrome.png', { tint: '#FFFFFF' });

// The mark as drawn inside the app - currently the login header. 512 so it
// still has headroom at 3x on the largest phones.
copy('brand/png/mark/jellylab-mark-dark-512.png', 'assets/images/mark.png');

// Web favicon. Larger than a favicon needs to be, so it stays sharp if Expo
// downsamples it for the tab and for the PWA install prompt.
copy('brand/png/icon/icon-192.png', 'assets/images/favicon.png');

console.log('done');
